package com.lldpractice.service;
import com.lldpractice.domain.*; import com.lldpractice.repo.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class PracticeService {
 final ProblemRepository problems; final AttemptRepository attempts; final EvaluationRepository evaluations; final RuleBasedEvaluator evaluator;
 public PracticeService(ProblemRepository p,AttemptRepository a,EvaluationRepository e,RuleBasedEvaluator r){problems=p;attempts=a;evaluations=e;evaluator=r;}
 public List<Problem> problems(){return problems.findAll();}
 @Transactional public Attempt start(Long problemId){Problem p=problems.findById(problemId).orElseThrow(); Attempt a=new Attempt();a.problem=p;return attempts.save(a);}
 public List<Attempt> attempts(){return attempts.findAllByOrderByCreatedAtDesc();}
 public Attempt get(Long id){return attempts.findById(id).orElseThrow();}
 @Transactional public Attempt save( Long id, Map<String,Object> body){Attempt a=get(id); if(body.containsKey("assumptions"))a.assumptions=String.valueOf(body.get("assumptions")); if(body.containsKey("classesResponsibilities"))a.classesResponsibilities=String.valueOf(body.get("classesResponsibilities")); if(body.containsKey("relationships"))a.relationships=String.valueOf(body.get("relationships")); if(body.containsKey("patterns"))a.patterns=String.valueOf(body.get("patterns")); if(body.containsKey("tradeoffs"))a.tradeoffs=String.valueOf(body.get("tradeoffs")); if(body.containsKey("diagramJson"))a.diagramJson=String.valueOf(body.get("diagramJson")); if(body.containsKey("challengeResponse"))a.challengeResponse=String.valueOf(body.get("challengeResponse")); if(body.containsKey("changeResponse"))a.changeResponse=String.valueOf(body.get("changeResponse")); return attempts.save(a);}
 @Transactional public Attempt submit(Long id,Map<String,Object> body){Attempt a=save(id,body);a.status=Attempt.Status.EVALUATING;a.submittedAt=Instant.now();attempts.save(a); EvaluationResult r=evaluator.evaluate(a.problem,a);a.score=r.totalScore();a.status=Attempt.Status.COMPLETED;attempts.save(a);Evaluation ev=evaluations.findByAttemptId(a.id).orElseGet(Evaluation::new);ev.attempt=a;ev.totalScore=r.totalScore();ev.feedbackJson=r.feedbackJson();evaluations.save(ev);return a;}
 public Evaluation evaluation(Long id){return evaluations.findByAttemptId(id).orElse(null);}
 public Map<String,Object> detail(Long id){Attempt a=get(id); Map<String,Object> out=new LinkedHashMap<>(); out.put("attempt",a); out.put("evaluation",evaluation(id)); return out;}
 public Map<String,Object> progress(){List<Attempt> all=attempts(); double avg=all.stream().filter(a->a.score!=null).mapToInt(a->a.score).average().orElse(0); Map<String,Object> m=new LinkedHashMap<>();m.put("attempts",all.size());m.put("completed",all.stream().filter(a->a.status==Attempt.Status.COMPLETED).count());m.put("averageScore",Math.round(avg));m.put("weakness","Extensibility");m.put("recommendations",List.of("Strategy","Dependency Inversion","Requirement Change"));return m;}

 public Map<String,Object> evaluateChallenge(Long id,String type,String response){ Attempt a=get(id); String r=response==null?"":response.trim(); int score=0; if(r.length()>=40)score+=30; String low=r.toLowerCase(); for(String k:List.of("interface","strategy","dependency","factory","service","abstraction","composition")){if(low.contains(k))score+=10;} score=Math.min(100,score); String feedback=score>=70?"The response identifies an extensibility seam and explains a concrete change.":score>=40?"The direction is reasonable; name the abstraction and explain how dependencies flow.":"Make the change concrete: identify the responsibility that changes, the abstraction that isolates it, and the classes affected."; Map<String,Object> out=new LinkedHashMap<>();out.put("type",type);out.put("score",score);out.put("feedback",feedback);out.put("attemptId",a.id);return out; }

 public Map<String,Object> compare(Long problemId){ List<Attempt> xs=attempts.findByProblemIdOrderByCreatedAtAsc(problemId); List<Map<String,Object>> rows=new ArrayList<>(); for(int i=0;i<xs.size();i++){Attempt a=xs.get(i); rows.add(Map.of("attempt",i+1,"id",a.id,"score",a.score==null?0:a.score,"status",a.status.toString()));} Map<String,Object> out=new LinkedHashMap<>(); out.put("attempts",rows); if(xs.size()>=2){Attempt first=xs.get(0),last=xs.get(xs.size()-1);out.put("improvement",(last.score==null?0:last.score)-(first.score==null?0:first.score));} else out.put("improvement",0); return out; }
}